[package]
name = "amiga_uae_view_plugin"
version = "0.1.0"
authors = ["Daniel Collin <daniel@collin.com>"]

[lib]
name = "amiga_uae_view_plugin"
crate-type = ["cdylib"]

[dependencies]
prodbg_api = { path = "../../../api/rust/prodbg" }
