# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    # install Qt with cache
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Install Tundra
      run: git clone --recursive https://github.com/deplinenoise/tundra.git && cd tundra && make && sudo make install && cd ..

    - name: Build Debug
      run: |
        export QT5_BIN=$Qt5_DIR/bin
        export QT5_INC=$Qt5_DIR/include
        export QT5_LIB=$Qt5_DIR/lib
        tundra2 linux-gcc-debug

  # Build macOS
#  build_macOS:
#    runs-on: macOS-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Install Qt
#      uses: jurplel/install-qt-action@v2
#    - name: Build Debug
#      run: export QT5_BIN=$Qt5_DIR/bin && export QT5_INC=$Qt5_DIR/include && export QT5_LIB=$Qt5_DIR/lib && scripts/mac_build_debug.sh

# Build Windows
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Build code test
      shell: cmd
      run: |
        set QT5_BIN=%Qt5_DIR%/bin
        set QT5_INC=%Qt5_DIR%/include
        set QT5_LIB=%Qt5_DIR%/lib
        echo %QT5_BIN%
        echo %QT5_INC%
        echo %QT5_LIB%
        bin\win32\tundra2.exe --unprotected win64-msvc-debug
